import { NextResponse } from "next/server"

import { isCountryCode } from "@/lib/countries"
import citiesByCountry from "@/lib/geo/cities.json"
import statesByCountry from "@/lib/geo/states.json"

const DATA: Record<"region" | "city", Record<string, string[]>> = {
  region: statesByCountry as Record<string, string[]>,
  city: citiesByCountry as Record<string, string[]>
}

type Kind = keyof typeof DATA

/** Below two characters every query matches half a country. */
const MIN_INPUT = 2
const MAX_INPUT = 120
const MAX_RESULTS = 6

/**
 * Region and city suggestions for the delivery address.
 *
 * Answered from lists committed into the repository rather than from a mapping
 * provider: no API key, no billing account to set up, no rate limit, and no
 * third party that can be down while somebody is trying to check out. The data
 * is regenerated by scripts/gen-geo.mjs.
 *
 * It also happens to be better for this shop than the free providers. Typing
 * "lag" here offers Lagos; Photon offered a village in Bauchi.
 *
 * Held on the server so the two megabytes of city names never reach a phone.
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url)
  const input = (searchParams.get("input") ?? "").trim()
  const country = (searchParams.get("country") ?? "").trim().toUpperCase()
  const kind = (searchParams.get("kind") ?? "") as Kind

  if (
    input.length < MIN_INPUT ||
    input.length > MAX_INPUT ||
    !isCountryCode(country) ||
    !(kind in DATA)
  ) {
    return NextResponse.json({ suggestions: [] })
  }

  const pool = DATA[kind][country] ?? []
  if (pool.length === 0) {
    return NextResponse.json({ suggestions: [] })
  }

  const needle = fold(input)
  const startsWith: string[] = []
  const contains: string[] = []

  for (const name of pool) {
    const folded = fold(name)
    if (folded.startsWith(needle)) {
      startsWith.push(name)
      // Enough prefix matches means nothing weaker will be shown anyway.
      if (startsWith.length >= MAX_RESULTS) break
    } else if (contains.length < MAX_RESULTS && folded.includes(needle)) {
      contains.push(name)
    }
  }

  // Prefix before substring, so "lag" leads with Lagos rather than with
  // somewhere that merely has those letters in the middle.
  const names = [...startsWith, ...contains].slice(0, MAX_RESULTS)

  const suggestions = names.map((name) => ({
    text: name,
    // A city carries its state so picking one can fill the field above it.
    secondary: kind === "city" ? stateContaining(country, name) : ""
  }))

  return NextResponse.json({ suggestions })
}

/** Case- and accent-insensitive, so "abeokuta" finds "Abéòkúta". */
function fold(value: string) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim()
}

/**
 * The state a city sits in, when the name gives it away.
 *
 * The city list carries no parent, so this only answers where a state shares
 * the city's name — Lagos, Kano, Enugu and plenty of other Nigerian capitals.
 * An empty string elsewhere simply means the buyer picks the state themselves.
 */
function stateContaining(country: string, city: string) {
  const states = DATA.region[country] ?? []
  const folded = fold(city)
  return states.find((state) => fold(state) === folded) ?? ""
}
